from enum import Enum

PACKET_DATABYTES = 1024 # 1 kilobyte of data
PACKET_SEQUENCEBYTES = 1
PACKET_CHECKSUMBYTES = 2
PACKET_MAXSIZE = PACKET_DATABYTES + PACKET_SEQUENCEBYTES + PACKET_CHECKSUMBYTES

RECEIVE_HOST = "localhost"
RECEIVE_PORT = 1337

SEND_HOST = "localhost"
SEND_PORT = 1337

SOCK_RECEIVE = None
SOCK_SEND = None

SOCK_RECEIVE_TIMEOUT = 2.0
SOCK_SEND_TIMEOUT = 0.5 # 1 second to be safe, could make this lower later

MAX_SEND_RETRIES = 10 # if at first you don't succeed, try again

# these will be used to detect incoming file types
COMMON_FILE_BYTES = {}
COMMON_FILE_BYTES["bmp"] = b'\x42\x4d'
COMMON_FILE_BYTES["jpg"] = b'\xff\xd8'
COMMON_FILE_BYTES["png"] = b'\x89\x50\x4e\x47'
#COMMON_FILE_BYTES["mp4"] = b'\x\x'

RECEIVE_STATE_WAIT0 = 0
RECEIVE_STATE_WAIT1 = 1

SEND_STATE_WAIT0 = 0
SEND_STATE_WAITACK0 = 1
SEND_STATE_WAIT1 = 2
SEND_STATE_WAITACK1 = 3

RECEIVER_STATE = RECEIVE_STATE_WAIT0
SENDER_STATE = SEND_STATE_WAIT0

SENDER_CORRUPT_RATE = 0 # percent
RECEIVER_CORRUPT_RATE = 0 # percent